In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.linear_model import LinearRegression
sns.set()

In [2]:
data = pd.read_csv(r'C:\Users\HP\Desktop\data science doc\1.02.+Multiple+linear+regression(2).csv')

In [3]:
data

SAT  Rand 1,2,3   GPA
0   1714           1  2.40
1   1664           3  2.52
2   1760           3  2.54
3   1685           3  2.74
4   1693           2  2.83
..   ...         ...   ...
79  1936           3  3.71
80  1810           1  3.71
81  1987           3  3.73
82  1962           1  3.76
83  2050           2  3.81

[84 rows x 3 columns]

In [4]:
# getting the details of the data
data.describe()

SAT  Rand 1,2,3        GPA
count    84.000000   84.000000  84.000000
mean   1845.273810    2.059524   3.330238
std     104.530661    0.855192   0.271617
min    1634.000000    1.000000   2.400000
25%    1772.000000    1.000000   3.190000
50%    1846.000000    2.000000   3.380000
75%    1934.000000    3.000000   3.502500
max    2050.000000    3.000000   3.810000

In [5]:
#creating an independent and dependent variables
x = data[['SAT', 'Rand 1,2,3']]
y = data['GPA']

In [6]:
x.shape

(84, 2)

In [7]:
#creating a regression
reg =LinearRegression()
reg.fit(x,y)

LinearRegression()

In [8]:
reg.coef_

array([ 0.00165354, -0.00826982])

In [9]:
reg.intercept_

0.29603261264909353

In [10]:
r2 = reg.score(x,y)

In [11]:
#creating r2 regression
n = x.shape[0]
p = x.shape[1]

In [12]:
Adjusted_R2 = 1-(1-r2)*(n-1)/(n-p-1)

In [13]:
Adjusted_R2

0.39203134825134

In [15]:
from sklearn.feature_selection import f_regression

In [16]:
f_regression(x,y)

(array([56.04804786,  0.17558437]), array([7.19951844e-11, 6.76291372e-01]))

In [17]:
p_value = f_regression(x,y)[1]

In [18]:
p_value

array([7.19951844e-11, 6.76291372e-01])

In [19]:
p_value.round(4)

array([0.    , 0.6763])

In [29]:
statistic_table = pd.DataFrame({'Feature':['SAT', 'Rand 1,2,3']})

In [30]:
statistic_table

Feature
0         SAT
1  Rand 1,2,3

In [31]:
statistic_table['Coefficent'] = reg.coef_

In [32]:
statistic_table['Intercept'] = reg.intercept_

In [33]:
statistic_table

Feature  Coefficent  Intercept
0         SAT    0.001654   0.296033
1  Rand 1,2,3   -0.008270   0.296033