In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import StandardScaler

In [2]:
df = pd.read_csv(r'C:\Users\HP\Desktop\real_estate_price_size_year(1).csv')

In [3]:
df.head(10)

price     size  year
0  234314.144   643.09  2015
1  228581.528   656.22  2009
2  281626.336   487.29  2018
3  401255.608  1504.75  2015
4  458674.256  1275.46  2009
5  245050.280   575.19  2006
6  265129.064   570.89  2015
7  175716.480   620.82  2006
8  331101.344   682.26  2018
9  218630.608   694.52  2009

In [4]:
df.describe()

price         size         year
count     100.000000   100.000000   100.000000
mean   292289.470160   853.024200  2012.600000
std     77051.727525   297.941951     4.729021
min    154282.128000   479.750000  2006.000000
25%    234280.148000   643.330000  2009.000000
50%    280590.716000   696.405000  2015.000000
75%    335723.696000  1029.322500  2018.000000
max    500681.128000  1842.510000  2018.000000

In [6]:
x = df[['size', 'year']]
y = df['price']

In [7]:
scaler = StandardScaler()

In [12]:
scaler.fit(x)

StandardScaler()

In [13]:
x_scaler = scaler.transform(x)

In [14]:
x_scaler

array([[-0.70816415,  0.51006137],
       [-0.66387316, -0.76509206],
       [-1.23371919,  1.14763808],
       [ 2.19844528,  0.51006137],
       [ 1.42498884, -0.76509206],
       [-0.937209  , -1.40266877],
       [-0.95171405,  0.51006137],
       [-0.78328682, -1.40266877],
       [-0.57603328,  1.14763808],
       [-0.53467702, -0.76509206],
       [ 0.69939906, -0.76509206],
       [ 3.33780001, -0.76509206],
       [-0.53467702,  0.51006137],
       [ 0.52699137,  1.14763808],
       [ 1.51100715, -1.40266877],
       [ 1.77668568, -1.40266877],
       [-0.54810263,  1.14763808],
       [-0.77276222, -1.40266877],
       [-0.58004747, -1.40266877],
       [ 0.58943055,  1.14763808],
       [-0.78365788,  0.51006137],
       [-1.02322731,  0.51006137],
       [ 1.19557293,  0.51006137],
       [-1.12884431,  0.51006137],
       [-1.10378093, -0.76509206],
       [ 0.84424715,  1.14763808],
       [-0.95171405,  1.14763808],
       [ 1.62279723,  0.51006137],
       [-0.58004747,

In [15]:
# creating regression with scaler feature
reg =LinearRegression()

In [16]:
reg.fit(x_scaler, y)

LinearRegression()

In [17]:
reg.coef_

array([67501.57614152, 13724.39708231])

In [18]:
reg.intercept_

292289.4701599997

In [19]:
summary = pd.DataFrame(data = ['size', 'year', 'price'], columns=['Title'])

In [20]:
summary

Title
0   size
1   year
2  price

In [21]:
summary['weight'] = reg.coef_[0],reg.coef_[1],reg.intercept_

In [22]:
summary

Title         weight
0   size   67501.576142
1   year   13724.397082
2  price  292289.470160

In [26]:
#making a pridiction
data =pd.DataFrame(data =[[643.0, 2015],[487.29,2018]], columns =['Size', 'year'])

In [27]:
data

Size  year
0  643.00  2015
1  487.29  2018

In [28]:
reg.predict(data)

C:\Users\HP\anaconda3\lib\site-packages\sklearn\base.py:443: UserWarning: X has feature names, but LinearRegression was fitted without feature names
  warnings.warn(


array([71350463.05000961, 60880965.82026014])

In [29]:
scaler_trans = scaler.transform(data)

C:\Users\HP\anaconda3\lib\site-packages\sklearn\base.py:493: FutureWarning: The feature names should match those that were passed during fit. Starting version 1.2, an error will be raised.
Feature names unseen at fit time:
- Size
Feature names seen at fit time, yet now missing:
- size

  warnings.warn(message, FutureWarning)


In [30]:
scaler_trans

array([[-0.70846775,  0.51006137],
       [-1.23371919,  1.14763808]])

In [31]:
new_trnas = reg.predict(scaler_trans)

In [32]:
new_trnas

array([251467.06524217, 224762.12124518])

In [43]:
r2 = reg.score(x_scaler, y)

In [44]:
r2

0.7764803683276793

In [45]:
# determingthe r2
x_scaler.shape

(100, 2)

In [48]:
#Determine the adjusted r-square
Ajusted_r2 = 1-(1-r2)*(100-1)/(100-2-1)

In [52]:
Ajusted_r2

0.77187171612825

In [53]:
from sklearn.feature_selection import f_regression

In [54]:
f_regression(x_scaler, y)

(array([285.92105192,   0.85525799]), array([8.12763222e-31, 3.57340758e-01]))

In [55]:
f_regression(x_scaler, y)[1]

array([8.12763222e-31, 3.57340758e-01])

In [56]:
P_value = f_regression(x_scaler, y)[1] 

In [57]:
P_value[0].

8.127632219789731e-31

In [60]:
P_value.round(3)

array([0.   , 0.357])