In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
sns.set()
from sklearn.linear_model import LinearRegression

In [2]:
# load data to work on
df = pd.read_csv(r'C:\Users\HP\Downloads\1.02.+Multiple+linear+regression(2).csv')

In [5]:
df.describe()

SAT  Rand 1,2,3        GPA
count    84.000000   84.000000  84.000000
mean   1845.273810    2.059524   3.330238
std     104.530661    0.855192   0.271617
min    1634.000000    1.000000   2.400000
25%    1772.000000    1.000000   3.190000
50%    1846.000000    2.000000   3.380000
75%    1934.000000    3.000000   3.502500
max    2050.000000    3.000000   3.810000

In [6]:
df.head(10)

SAT  Rand 1,2,3   GPA
0  1714           1  2.40
1  1664           3  2.52
2  1760           3  2.54
3  1685           3  2.74
4  1693           2  2.83
5  1670           1  2.91
6  1764           2  3.00
7  1764           1  3.00
8  1792           2  3.01
9  1850           3  3.01

In [13]:
#creating independent variable
x = df[['SAT', 'Rand 1,2,3']]

#creating dependent variable
y = df['GPA']

In [14]:
#creating regression
reg = LinearRegression()
reg.fit(x,y)

LinearRegression()

In [16]:
reg.score(x,y)

0.4066811952814282

In [17]:
reg.intercept_

0.29603261264909353

In [18]:
reg.coef_

array([ 0.00165354, -0.00826982])

In [19]:
x.shape

(84, 2)

In [20]:
# calculating Ajusted r_square value
r2 = reg.score(x,y)
n = 84
p = 2

In [21]:
Adjusted_r2 = 1-(1-r2)*(84-1)/(84-2-1)

In [22]:
Adjusted_r2

0.39203134825134

In [24]:
# f regression
from sklearn.feature_selection import f_regression

In [25]:
f_regression(x,y)

(array([56.04804786,  0.17558437]), array([7.19951844e-11, 6.76291372e-01]))

In [26]:
f_regression(x,y)[1]

array([7.19951844e-11, 6.76291372e-01])

In [27]:
p_values = f_regression(x,y)[1]

In [28]:
p_values

array([7.19951844e-11, 6.76291372e-01])

In [30]:
p_value =p_values[0:1]

In [33]:
p_value.round(4)

array([0.])

In [43]:
table = pd.DataFrame(data = [reg.score(x,y)], columns = ['R2'])

In [44]:
table

R2
0  0.406681

In [47]:
table['Adjusted_r2'] =[Adjusted_r2]

In [48]:
table

R2 0.39203134825134  Adjusted_r2
0  0.406681      Adjusted_r2     0.392031

In [49]:
table['Intercept'] = [reg.intercept_]

In [50]:
table

R2 0.39203134825134  Adjusted_r2  Intercept
0  0.406681      Adjusted_r2     0.392031   0.296033

In [51]:
table['P_value'] = p_value

In [52]:
table

R2 0.39203134825134  Adjusted_r2  Intercept       P_value
0  0.406681      Adjusted_r2     0.392031   0.296033  7.199518e-11

In [53]:
table.columns

Index(['R2', 0.39203134825134, 'Adjusted_r2', 'Intercept', 'P_value'], dtype='object')

In [54]:
table =table[['R2', 'Adjusted_r2', 'Intercept', 'P_value']]

In [55]:
table

R2  Adjusted_r2  Intercept       P_value
0  0.406681     0.392031   0.296033  7.199518e-11

In [56]:
# standardization of data
from sklearn.preprocessing import StandardScaler

In [60]:
scaler = StandardScaler()

In [61]:
scaler.fit(x)

StandardScaler()

In [63]:
xscaler = scaler.transform(x)

In [64]:
xscaler

array([[-1.26338288, -1.24637147],
       [-1.74458431,  1.10632974],
       [-0.82067757,  1.10632974],
       [-1.54247971,  1.10632974],
       [-1.46548748, -0.07002087],
       [-1.68684014, -1.24637147],
       [-0.78218146, -0.07002087],
       [-0.78218146, -1.24637147],
       [-0.51270866, -0.07002087],
       [ 0.04548499,  1.10632974],
       [-1.06127829,  1.10632974],
       [-0.67631715, -0.07002087],
       [-1.06127829, -1.24637147],
       [-1.28263094,  1.10632974],
       [-0.6955652 , -0.07002087],
       [ 0.25721362, -0.07002087],
       [-0.86879772,  1.10632974],
       [-1.64834403, -0.07002087],
       [-0.03150724,  1.10632974],
       [-0.57045283,  1.10632974],
       [-0.81105355,  1.10632974],
       [-1.18639066,  1.10632974],
       [-1.75420834,  1.10632974],
       [-1.52323165, -1.24637147],
       [ 1.23886453, -1.24637147],
       [-0.18549169, -1.24637147],
       [-0.5608288 , -1.24637147],
       [-0.23361183,  1.10632974],
       [ 1.68156984,

In [66]:
reg1 =reg.fit(xscaler,y)

In [68]:
reg1.coef_

array([ 0.17181389, -0.00703007])

In [69]:
reg1.intercept_

3.330238095238095

In [70]:
reg_summary = pd.DataFrame([['GPA'],['SAT'],['Rand 1,2,3']], columns=['Features'])

In [71]:
reg_summary

Features
0         GPA
1         SAT
2  Rand 1,2,3

In [73]:
reg_summary['Weight'] =  reg1.intercept_,reg1.coef_[0],reg1.coef_[1]

In [74]:
reg_summary

Features    Weight
0         GPA  3.330238
1         SAT  0.171814
2  Rand 1,2,3 -0.007030

In [75]:
new_data1 = pd.DataFrame(data =[[1700,2],[1800,1]], columns = ['SAT', 'Rand 1,2,3'])

In [76]:
reg.predict(new_data1)

C:\Users\HP\anaconda3\lib\site-packages\sklearn\base.py:443: UserWarning: X has feature names, but LinearRegression was fitted without feature names
  warnings.warn(


array([295.39979563, 312.58821497])

In [77]:
new_data1_scaler = scaler.transform(new_data1)

In [78]:
new_data1_scaler

array([[-1.39811928, -0.07002087],
       [-0.43571643, -1.24637147]])

In [79]:
reg.predict(new_data1_scaler)

array([3.09051403, 3.26413803])