In [1]:
import numpy as np
import pandas as pd

In [3]:
data = np.array([[21,3,4,67,32,1], [21,6,34,54,64,36]])

In [4]:
data.reshape(3,4)

array([[21,  3,  4, 67],
       [32,  1, 21,  6],
       [34, 54, 64, 36]])

In [5]:
data.reshape(4,3)

array([[21,  3,  4],
       [67, 32,  1],
       [21,  6, 34],
       [54, 64, 36]])

In [6]:
data.resize(3,4)

In [7]:
data

array([[21,  3,  4, 67],
       [32,  1, 21,  6],
       [34, 54, 64, 36]])

In [9]:
data.ravel()

array([21,  3,  4, 67, 32,  1, 21,  6, 34, 54, 64, 36])

In [10]:
data1 = np.array([23,45,67,98,12,2])

In [11]:
data2 = np.array([12,43,56,12,21,21])

In [15]:
np.hstack((data1, data2))

array([23, 45, 67, 98, 12,  2, 12, 43, 56, 12, 21, 21])

In [19]:
np.hsplit(data,2)

[array([[21,  3],
        [32,  1],
        [34, 54]]),
 array([[ 4, 67],
        [21,  6],
        [64, 36]])]

In [20]:
first_array = np.array([2,3,5,7,8,12])

In [21]:
first_array

array([ 2,  3,  5,  7,  8, 12])

In [24]:
first_array.reshape(3,2)

array([[ 2,  3],
       [ 5,  7],
       [ 8, 12]])

In [26]:
zero_array =np.zeros((3,3))

In [27]:
zero_array

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [28]:
one_array = np.ones((4,3))

In [30]:
print(one_array)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [31]:
one_array

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [41]:
arrange_np = np.arange(15)

In [42]:
print(arrange_np)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [43]:
arrange_np.reshape(3,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [53]:
np_linespace = np.linspace(2,10,5)

In [54]:
print(np_linespace)

[ 2.  4.  6.  8. 10.]


In [56]:
dataframe = pd.DataFrame({'Hosting city':['Taiwan','NIgeria','Ghana', 'France'],'Year':[2004,2005,2003,2011], 'Percitipated Country':[201,411,532,162]})

In [57]:
dataframe

Hosting city  Year  Percitipated Country
0       Taiwan  2004                   201
1      NIgeria  2005                   411
2        Ghana  2003                   532
3       France  2011                   162

In [62]:
dataframe.rename(index={0:'a',1:'b',2:'c',3:'d'})

Hosting city  Year  Percitipated Country
a       Taiwan  2004                   201
b      NIgeria  2005                   411
c        Ghana  2003                   532
d       France  2011                   162